# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/client/v2/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fibc/core/client/v2/config.proto\x12\x12ibc.core.client.v2\"3\n\x06\x43onfig\x12)\n\x10\x61llowed_relayers\x18\x01 \x03(\tR\x0f\x61llowedRelayersB\xce\x01\n\x16\x63om.ibc.core.client.v2B\x0b\x43onfigProtoP\x01Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types\xa2\x02\x03ICC\xaa\x02\x12Ibc.Core.Client.V2\xca\x02\x12Ibc\\Core\\Client\\V2\xe2\x02\x1eIbc\\Core\\Client\\V2\\GPBMetadata\xea\x02\x15Ibc::Core::Client::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.client.v2.config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.ibc.core.client.v2B\013ConfigProtoP\001Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types\242\002\003ICC\252\002\022Ibc.Core.Client.V2\312\002\022Ibc\\Core\\Client\\V2\342\002\036Ibc\\Core\\Client\\V2\\GPBMetadata\352\002\025Ibc::Core::Client::V2'
  _globals['_CONFIG']._serialized_start=55
  _globals['_CONFIG']._serialized_end=106
# @@protoc_insertion_point(module_scope)
