# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/client/v2/counterparty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ibc/core/client/v2/counterparty.proto\x12\x12ibc.core.client.v2\"T\n\x10\x43ounterpartyInfo\x12#\n\rmerkle_prefix\x18\x01 \x03(\x0cR\x0cmerklePrefix\x12\x1b\n\tclient_id\x18\x02 \x01(\tR\x08\x63lientIdB\xd4\x01\n\x16\x63om.ibc.core.client.v2B\x11\x43ounterpartyProtoP\x01Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types\xa2\x02\x03ICC\xaa\x02\x12Ibc.Core.Client.V2\xca\x02\x12Ibc\\Core\\Client\\V2\xe2\x02\x1eIbc\\Core\\Client\\V2\\GPBMetadata\xea\x02\x15Ibc::Core::Client::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.client.v2.counterparty_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.ibc.core.client.v2B\021CounterpartyProtoP\001Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types\242\002\003ICC\252\002\022Ibc.Core.Client.V2\312\002\022Ibc\\Core\\Client\\V2\342\002\036Ibc\\Core\\Client\\V2\\GPBMetadata\352\002\025Ibc::Core::Client::V2'
  _globals['_COUNTERPARTYINFO']._serialized_start=61
  _globals['_COUNTERPARTYINFO']._serialized_end=145
# @@protoc_insertion_point(module_scope)
