# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/client/v2/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from ibc.core.client.v2 import config_pb2 as ibc_dot_core_dot_client_dot_v2_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bibc/core/client/v2/tx.proto\x12\x12ibc.core.client.v2\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\x1a\x1fibc/core/client/v2/config.proto\"\xd3\x01\n\x17MsgRegisterCounterparty\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12<\n\x1a\x63ounterparty_merkle_prefix\x18\x02 \x03(\x0cR\x18\x63ounterpartyMerklePrefix\x12\x34\n\x16\x63ounterparty_client_id\x18\x03 \x01(\tR\x14\x63ounterpartyClientId\x12\x16\n\x06signer\x18\x04 \x01(\tR\x06signer:\x0f\x88\xa0\x1f\x00\x82\xe7\xb0*\x06signer\"!\n\x1fMsgRegisterCounterpartyResponse\"\x97\x01\n\x15MsgUpdateClientConfig\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12\x38\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1a.ibc.core.client.v2.ConfigB\x04\xc8\xde\x1f\x00R\x06\x63onfig\x12\x16\n\x06signer\x18\x03 \x01(\tR\x06signer:\x0f\x88\xa0\x1f\x00\x82\xe7\xb0*\x06signer\"\x1f\n\x1dMsgUpdateClientConfigResponse2\xfa\x01\n\x03Msg\x12x\n\x14RegisterCounterparty\x12+.ibc.core.client.v2.MsgRegisterCounterparty\x1a\x33.ibc.core.client.v2.MsgRegisterCounterpartyResponse\x12r\n\x12UpdateClientConfig\x12).ibc.core.client.v2.MsgUpdateClientConfig\x1a\x31.ibc.core.client.v2.MsgUpdateClientConfigResponse\x1a\x05\x80\xe7\xb0*\x01\x42\xca\x01\n\x16\x63om.ibc.core.client.v2B\x07TxProtoP\x01Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types\xa2\x02\x03ICC\xaa\x02\x12Ibc.Core.Client.V2\xca\x02\x12Ibc\\Core\\Client\\V2\xe2\x02\x1eIbc\\Core\\Client\\V2\\GPBMetadata\xea\x02\x15Ibc::Core::Client::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.client.v2.tx_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.ibc.core.client.v2B\007TxProtoP\001Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types\242\002\003ICC\252\002\022Ibc.Core.Client.V2\312\002\022Ibc\\Core\\Client\\V2\342\002\036Ibc\\Core\\Client\\V2\\GPBMetadata\352\002\025Ibc::Core::Client::V2'
  _MSGREGISTERCOUNTERPARTY._options = None
  _MSGREGISTERCOUNTERPARTY._serialized_options = b'\210\240\037\000\202\347\260*\006signer'
  _MSGUPDATECLIENTCONFIG.fields_by_name['config']._options = None
  _MSGUPDATECLIENTCONFIG.fields_by_name['config']._serialized_options = b'\310\336\037\000'
  _MSGUPDATECLIENTCONFIG._options = None
  _MSGUPDATECLIENTCONFIG._serialized_options = b'\210\240\037\000\202\347\260*\006signer'
  _MSG._options = None
  _MSG._serialized_options = b'\200\347\260*\001'
  _globals['_MSGREGISTERCOUNTERPARTY']._serialized_start=132
  _globals['_MSGREGISTERCOUNTERPARTY']._serialized_end=343
  _globals['_MSGREGISTERCOUNTERPARTYRESPONSE']._serialized_start=345
  _globals['_MSGREGISTERCOUNTERPARTYRESPONSE']._serialized_end=378
  _globals['_MSGUPDATECLIENTCONFIG']._serialized_start=381
  _globals['_MSGUPDATECLIENTCONFIG']._serialized_end=532
  _globals['_MSGUPDATECLIENTCONFIGRESPONSE']._serialized_start=534
  _globals['_MSGUPDATECLIENTCONFIGRESPONSE']._serialized_end=565
  _globals['_MSG']._serialized_start=568
  _globals['_MSG']._serialized_end=818
# @@protoc_insertion_point(module_scope)
