# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/client/v1/client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fibc/core/client/v1/client.proto\x12\x12ibc.core.client.v1\x1a\x14gogoproto/gogo.proto\x1a\x19google/protobuf/any.proto\"m\n\x15IdentifiedClientState\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12\x37\n\x0c\x63lient_state\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyR\x0b\x63lientState\"\x93\x01\n\x18\x43onsensusStateWithHeight\x12\x38\n\x06height\x18\x01 \x01(\x0b\x32\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x06height\x12=\n\x0f\x63onsensus_state\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyR\x0e\x63onsensusState\"\x93\x01\n\x15\x43lientConsensusStates\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12]\n\x10\x63onsensus_states\x18\x02 \x03(\x0b\x32,.ibc.core.client.v1.ConsensusStateWithHeightB\x04\xc8\xde\x1f\x00R\x0f\x63onsensusStates\"\x8e\x01\n\x06Height\x12<\n\x0frevision_number\x18\x01 \x01(\x04\x42\x13\xea\xde\x1f\x0frevision_numberR\x0erevisionNumber\x12<\n\x0frevision_height\x18\x02 \x01(\x04\x42\x13\xea\xde\x1f\x0frevision_heightR\x0erevisionHeight:\x08\x88\xa0\x1f\x00\x98\xa0\x1f\x00\"1\n\x06Params\x12\'\n\x0f\x61llowed_clients\x18\x01 \x03(\tR\x0e\x61llowedClientsB\xcb\x01\n\x16\x63om.ibc.core.client.v1B\x0b\x43lientProtoP\x01Z9github.com/cosmos/ibc-go/v10/modules/core/02-client/types\xa2\x02\x03ICC\xaa\x02\x12Ibc.Core.Client.V1\xca\x02\x12Ibc\\Core\\Client\\V1\xe2\x02\x1eIbc\\Core\\Client\\V1\\GPBMetadata\xea\x02\x15Ibc::Core::Client::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.client.v1.client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.ibc.core.client.v1B\013ClientProtoP\001Z9github.com/cosmos/ibc-go/v10/modules/core/02-client/types\242\002\003ICC\252\002\022Ibc.Core.Client.V1\312\002\022Ibc\\Core\\Client\\V1\342\002\036Ibc\\Core\\Client\\V1\\GPBMetadata\352\002\025Ibc::Core::Client::V1'
  _CONSENSUSSTATEWITHHEIGHT.fields_by_name['height']._options = None
  _CONSENSUSSTATEWITHHEIGHT.fields_by_name['height']._serialized_options = b'\310\336\037\000'
  _CLIENTCONSENSUSSTATES.fields_by_name['consensus_states']._options = None
  _CLIENTCONSENSUSSTATES.fields_by_name['consensus_states']._serialized_options = b'\310\336\037\000'
  _HEIGHT.fields_by_name['revision_number']._options = None
  _HEIGHT.fields_by_name['revision_number']._serialized_options = b'\352\336\037\017revision_number'
  _HEIGHT.fields_by_name['revision_height']._options = None
  _HEIGHT.fields_by_name['revision_height']._serialized_options = b'\352\336\037\017revision_height'
  _HEIGHT._options = None
  _HEIGHT._serialized_options = b'\210\240\037\000\230\240\037\000'
  _globals['_IDENTIFIEDCLIENTSTATE']._serialized_start=104
  _globals['_IDENTIFIEDCLIENTSTATE']._serialized_end=213
  _globals['_CONSENSUSSTATEWITHHEIGHT']._serialized_start=216
  _globals['_CONSENSUSSTATEWITHHEIGHT']._serialized_end=363
  _globals['_CLIENTCONSENSUSSTATES']._serialized_start=366
  _globals['_CLIENTCONSENSUSSTATES']._serialized_end=513
  _globals['_HEIGHT']._serialized_start=516
  _globals['_HEIGHT']._serialized_end=658
  _globals['_PARAMS']._serialized_start=660
  _globals['_PARAMS']._serialized_end=709
# @@protoc_insertion_point(module_scope)
