# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from relayer import relayer_pb2 as relayer_dot_relayer__pb2


class RelayerServiceStub(object):
    """The relayer service definition
    Each relayer service is defined between two chains.
    One chain is the source chain, and the other chain is the target chain.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RelayByTx = channel.unary_unary(
                '/relayer.RelayerService/RelayByTx',
                request_serializer=relayer_dot_relayer__pb2.RelayByTxRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.RelayByTxResponse.FromString,
                )
        self.CreateClient = channel.unary_unary(
                '/relayer.RelayerService/CreateClient',
                request_serializer=relayer_dot_relayer__pb2.CreateClientRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.CreateClientResponse.FromString,
                )
        self.UpdateClient = channel.unary_unary(
                '/relayer.RelayerService/UpdateClient',
                request_serializer=relayer_dot_relayer__pb2.UpdateClientRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.UpdateClientResponse.FromString,
                )
        self.Info = channel.unary_unary(
                '/relayer.RelayerService/Info',
                request_serializer=relayer_dot_relayer__pb2.InfoRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.InfoResponse.FromString,
                )


class RelayerServiceServicer(object):
    """The relayer service definition
    Each relayer service is defined between two chains.
    One chain is the source chain, and the other chain is the target chain.
    """

    def RelayByTx(self, request, context):
        """Relay the ibc packets produced by the results of transactions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateClient(self, request, context):
        """Create a new ibc client on the target (destination) chain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClient(self, request, context):
        """Update the ibc client on the target (destination) chain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Request relayer information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RelayByTx': grpc.unary_unary_rpc_method_handler(
                    servicer.RelayByTx,
                    request_deserializer=relayer_dot_relayer__pb2.RelayByTxRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.RelayByTxResponse.SerializeToString,
            ),
            'CreateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClient,
                    request_deserializer=relayer_dot_relayer__pb2.CreateClientRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.CreateClientResponse.SerializeToString,
            ),
            'UpdateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClient,
                    request_deserializer=relayer_dot_relayer__pb2.UpdateClientRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.UpdateClientResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=relayer_dot_relayer__pb2.InfoRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relayer.RelayerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RelayerService(object):
    """The relayer service definition
    Each relayer service is defined between two chains.
    One chain is the source chain, and the other chain is the target chain.
    """

    @staticmethod
    def RelayByTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relayer.RelayerService/RelayByTx',
            relayer_dot_relayer__pb2.RelayByTxRequest.SerializeToString,
            relayer_dot_relayer__pb2.RelayByTxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relayer.RelayerService/CreateClient',
            relayer_dot_relayer__pb2.CreateClientRequest.SerializeToString,
            relayer_dot_relayer__pb2.CreateClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relayer.RelayerService/UpdateClient',
            relayer_dot_relayer__pb2.UpdateClientRequest.SerializeToString,
            relayer_dot_relayer__pb2.UpdateClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relayer.RelayerService/Info',
            relayer_dot_relayer__pb2.InfoRequest.SerializeToString,
            relayer_dot_relayer__pb2.InfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
