# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethermint/evm/v1/access_tuple.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ethermint/evm/v1/access_tuple.proto\x12\x10\x65thermint.evm.v1\x1a\x14gogoproto/gogo.proto\"a\n\x0b\x41\x63\x63\x65ssTuple\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x32\n\x0cstorage_keys\x18\x02 \x03(\tB\x0f\xea\xde\x1f\x0bstorageKeysR\x0bstorageKeys:\x04\x88\xa0\x1f\x00\x42\xb2\x01\n\x14\x63om.ethermint.evm.v1B\x10\x41\x63\x63\x65ssTupleProtoP\x01Z&github.com/evmos/ethermint/x/evm/types\xa2\x02\x03\x45\x45X\xaa\x02\x10\x45thermint.Evm.V1\xca\x02\x10\x45thermint\\Evm\\V1\xe2\x02\x1c\x45thermint\\Evm\\V1\\GPBMetadata\xea\x02\x12\x45thermint::Evm::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethermint.evm.v1.access_tuple_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.ethermint.evm.v1B\020AccessTupleProtoP\001Z&github.com/evmos/ethermint/x/evm/types\242\002\003EEX\252\002\020Ethermint.Evm.V1\312\002\020Ethermint\\Evm\\V1\342\002\034Ethermint\\Evm\\V1\\GPBMetadata\352\002\022Ethermint::Evm::V1'
  _ACCESSTUPLE.fields_by_name['storage_keys']._options = None
  _ACCESSTUPLE.fields_by_name['storage_keys']._serialized_options = b'\352\336\037\013storageKeys'
  _ACCESSTUPLE._options = None
  _ACCESSTUPLE._serialized_options = b'\210\240\037\000'
  _globals['_ACCESSTUPLE']._serialized_start=79
  _globals['_ACCESSTUPLE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
