# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/commitment/v2/commitment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ibc/core/commitment/v2/commitment.proto\x12\x16ibc.core.commitment.v2\"\'\n\nMerklePath\x12\x19\n\x08key_path\x18\x01 \x03(\x0cR\x07keyPathB\xea\x01\n\x1a\x63om.ibc.core.commitment.v2B\x0f\x43ommitmentProtoP\x01Z@github.com/cosmos/ibc-go/v10/modules/core/23-commitment/types/v2\xa2\x02\x03ICC\xaa\x02\x16Ibc.Core.Commitment.V2\xca\x02\x16Ibc\\Core\\Commitment\\V2\xe2\x02\"Ibc\\Core\\Commitment\\V2\\GPBMetadata\xea\x02\x19Ibc::Core::Commitment::V2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.commitment.v2.commitment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.ibc.core.commitment.v2B\017CommitmentProtoP\001Z@github.com/cosmos/ibc-go/v10/modules/core/23-commitment/types/v2\242\002\003ICC\252\002\026Ibc.Core.Commitment.V2\312\002\026Ibc\\Core\\Commitment\\V2\342\002\"Ibc\\Core\\Commitment\\V2\\GPBMetadata\352\002\031Ibc::Core::Commitment::V2'
  _globals['_MERKLEPATH']._serialized_start=67
  _globals['_MERKLEPATH']._serialized_end=106
# @@protoc_insertion_point(module_scope)
